IMAGE_NAME = "centos/7"
COUNTER = 2
Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", path: "init.sh"

  config.vm.define "master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.hostname = "master.k8s.com"
    master.vm.provision :shell, :inline => "sed 's/127.0.0.1.*master/10.0.0.10 master/' -i /etc/hosts"
    master.vm.provision "shell", path: "master.sh"
  end

  (1..COUNTER).each do |i|
    config.vm.define "worker#{i}" do |worker|
        worker.vm.box = IMAGE_NAME
        worker.vm.network "private_network", ip: "10.0.0.#{i + 11}"
        worker.vm.hostname = "worker#{i}.k8s.com"
        worker.vm.provision "shell", path: "worker.sh"
    end
  end
end
